// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: semantic_search.proto
// Protobuf C++ Version: 6.31.0

#ifndef semantic_5fsearch_2eproto_2epb_2eh
#define semantic_5fsearch_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_semantic_5fsearch_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_semantic_5fsearch_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_semantic_5fsearch_2eproto;
}  // extern "C"
class pyInferenceReq;
struct pyInferenceReqDefaultTypeInternal;
extern pyInferenceReqDefaultTypeInternal _pyInferenceReq_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull pyInferenceReq_class_data_;
class pyInferenceResp;
struct pyInferenceRespDefaultTypeInternal;
extern pyInferenceRespDefaultTypeInternal _pyInferenceResp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull pyInferenceResp_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class pyInferenceResp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pyInferenceResp) */ {
 public:
  inline pyInferenceResp() : pyInferenceResp(nullptr) {}
  ~pyInferenceResp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(pyInferenceResp* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(pyInferenceResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR pyInferenceResp(::google::protobuf::internal::ConstantInitialized);

  inline pyInferenceResp(const pyInferenceResp& from) : pyInferenceResp(nullptr, from) {}
  inline pyInferenceResp(pyInferenceResp&& from) noexcept
      : pyInferenceResp(nullptr, ::std::move(from)) {}
  inline pyInferenceResp& operator=(const pyInferenceResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline pyInferenceResp& operator=(pyInferenceResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const pyInferenceResp& default_instance() {
    return *reinterpret_cast<const pyInferenceResp*>(
        &_pyInferenceResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(pyInferenceResp& a, pyInferenceResp& b) { a.Swap(&b); }
  inline void Swap(pyInferenceResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(pyInferenceResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  pyInferenceResp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<pyInferenceResp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const pyInferenceResp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const pyInferenceResp& from) { pyInferenceResp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(pyInferenceResp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pyInferenceResp"; }

 protected:
  explicit pyInferenceResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  pyInferenceResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const pyInferenceResp& from);
  pyInferenceResp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, pyInferenceResp&& from) noexcept
      : pyInferenceResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDocIdFieldNumber = 1,
  };
  // repeated int32 doc_id = 1;
  int doc_id_size() const;
  private:
  int _internal_doc_id_size() const;

  public:
  void clear_doc_id() ;
  ::int32_t doc_id(int index) const;
  void set_doc_id(int index, ::int32_t value);
  void add_doc_id(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& doc_id() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_doc_id();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_doc_id() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_doc_id();

  public:
  // @@protoc_insertion_point(class_scope:pyInferenceResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const pyInferenceResp& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> doc_id_;
    ::google::protobuf::internal::CachedSize _doc_id_cached_byte_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_semantic_5fsearch_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull pyInferenceResp_class_data_;
// -------------------------------------------------------------------

class pyInferenceReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pyInferenceReq) */ {
 public:
  inline pyInferenceReq() : pyInferenceReq(nullptr) {}
  ~pyInferenceReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(pyInferenceReq* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(pyInferenceReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR pyInferenceReq(::google::protobuf::internal::ConstantInitialized);

  inline pyInferenceReq(const pyInferenceReq& from) : pyInferenceReq(nullptr, from) {}
  inline pyInferenceReq(pyInferenceReq&& from) noexcept
      : pyInferenceReq(nullptr, ::std::move(from)) {}
  inline pyInferenceReq& operator=(const pyInferenceReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline pyInferenceReq& operator=(pyInferenceReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const pyInferenceReq& default_instance() {
    return *reinterpret_cast<const pyInferenceReq*>(
        &_pyInferenceReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(pyInferenceReq& a, pyInferenceReq& b) { a.Swap(&b); }
  inline void Swap(pyInferenceReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(pyInferenceReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  pyInferenceReq* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<pyInferenceReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const pyInferenceReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const pyInferenceReq& from) { pyInferenceReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(pyInferenceReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pyInferenceReq"; }

 protected:
  explicit pyInferenceReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  pyInferenceReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const pyInferenceReq& from);
  pyInferenceReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, pyInferenceReq&& from) noexcept
      : pyInferenceReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQueryFieldNumber = 1,
  };
  // string query = 1;
  void clear_query() ;
  const ::std::string& query() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_query(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_query();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_query();
  void set_allocated_query(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_query() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_query(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_query();

  public:
  // @@protoc_insertion_point(class_scope:pyInferenceReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 28,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const pyInferenceReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr query_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_semantic_5fsearch_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull pyInferenceReq_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// pyInferenceReq

// string query = 1;
inline void pyInferenceReq::clear_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.query_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& pyInferenceReq::query() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pyInferenceReq.query)
  return _internal_query();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void pyInferenceReq::set_query(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.query_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:pyInferenceReq.query)
}
inline ::std::string* PROTOBUF_NONNULL pyInferenceReq::mutable_query()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_query();
  // @@protoc_insertion_point(field_mutable:pyInferenceReq.query)
  return _s;
}
inline const ::std::string& pyInferenceReq::_internal_query() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.query_.Get();
}
inline void pyInferenceReq::_internal_set_query(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.query_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL pyInferenceReq::_internal_mutable_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.query_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE pyInferenceReq::release_query() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:pyInferenceReq.query)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.query_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.query_.Set("", GetArena());
  }
  return released;
}
inline void pyInferenceReq::set_allocated_query(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.query_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.query_.IsDefault()) {
    _impl_.query_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:pyInferenceReq.query)
}

// -------------------------------------------------------------------

// pyInferenceResp

// repeated int32 doc_id = 1;
inline int pyInferenceResp::_internal_doc_id_size() const {
  return _internal_doc_id().size();
}
inline int pyInferenceResp::doc_id_size() const {
  return _internal_doc_id_size();
}
inline void pyInferenceResp::clear_doc_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.doc_id_.Clear();
}
inline ::int32_t pyInferenceResp::doc_id(int index) const {
  // @@protoc_insertion_point(field_get:pyInferenceResp.doc_id)
  return _internal_doc_id().Get(index);
}
inline void pyInferenceResp::set_doc_id(int index, ::int32_t value) {
  _internal_mutable_doc_id()->Set(index, value);
  // @@protoc_insertion_point(field_set:pyInferenceResp.doc_id)
}
inline void pyInferenceResp::add_doc_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_doc_id()->Add(value);
  // @@protoc_insertion_point(field_add:pyInferenceResp.doc_id)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& pyInferenceResp::doc_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:pyInferenceResp.doc_id)
  return _internal_doc_id();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL pyInferenceResp::mutable_doc_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:pyInferenceResp.doc_id)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_doc_id();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
pyInferenceResp::_internal_doc_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.doc_id_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
pyInferenceResp::_internal_mutable_doc_id() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.doc_id_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // semantic_5fsearch_2eproto_2epb_2eh
