// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: semantic_search.proto
#ifndef GRPC_semantic_5fsearch_2eproto__INCLUDED
#define GRPC_semantic_5fsearch_2eproto__INCLUDED

#include "semantic_search.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class SemanticSearch final {
 public:
  static constexpr char const* service_full_name() {
    return "SemanticSearch";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status inference(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::pyInferenceResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pyInferenceResp>> Asyncinference(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pyInferenceResp>>(AsyncinferenceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pyInferenceResp>> PrepareAsyncinference(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pyInferenceResp>>(PrepareAsyncinferenceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void inference(::grpc::ClientContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void inference(::grpc::ClientContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pyInferenceResp>* AsyncinferenceRaw(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pyInferenceResp>* PrepareAsyncinferenceRaw(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status inference(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::pyInferenceResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pyInferenceResp>> Asyncinference(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pyInferenceResp>>(AsyncinferenceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pyInferenceResp>> PrepareAsyncinference(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pyInferenceResp>>(PrepareAsyncinferenceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void inference(::grpc::ClientContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response, std::function<void(::grpc::Status)>) override;
      void inference(::grpc::ClientContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pyInferenceResp>* AsyncinferenceRaw(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pyInferenceResp>* PrepareAsyncinferenceRaw(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_inference_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status inference(::grpc::ServerContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_inference() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status inference(::grpc::ServerContext* /*context*/, const ::pyInferenceReq* /*request*/, ::pyInferenceResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestinference(::grpc::ServerContext* context, ::pyInferenceReq* request, ::grpc::ServerAsyncResponseWriter< ::pyInferenceResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_inference<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_inference() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pyInferenceReq, ::pyInferenceResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response) { return this->inference(context, request, response); }));}
    void SetMessageAllocatorFor_inference(
        ::grpc::MessageAllocator< ::pyInferenceReq, ::pyInferenceResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pyInferenceReq, ::pyInferenceResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status inference(::grpc::ServerContext* /*context*/, const ::pyInferenceReq* /*request*/, ::pyInferenceResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* inference(
      ::grpc::CallbackServerContext* /*context*/, const ::pyInferenceReq* /*request*/, ::pyInferenceResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_inference<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_inference() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status inference(::grpc::ServerContext* /*context*/, const ::pyInferenceReq* /*request*/, ::pyInferenceResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_inference() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status inference(::grpc::ServerContext* /*context*/, const ::pyInferenceReq* /*request*/, ::pyInferenceResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestinference(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_inference() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->inference(context, request, response); }));
    }
    ~WithRawCallbackMethod_inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status inference(::grpc::ServerContext* /*context*/, const ::pyInferenceReq* /*request*/, ::pyInferenceResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* inference(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_inference : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_inference() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pyInferenceReq, ::pyInferenceResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pyInferenceReq, ::pyInferenceResp>* streamer) {
                       return this->Streamedinference(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_inference() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status inference(::grpc::ServerContext* /*context*/, const ::pyInferenceReq* /*request*/, ::pyInferenceResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedinference(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pyInferenceReq,::pyInferenceResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_inference<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_inference<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_semantic_5fsearch_2eproto__INCLUDED
