# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sementic_search.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sementic_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sementic_search.proto\"\x1f\n\x0epyInferenceReq\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\x0fpyInferenceResp\x12\x0e\n\x06\x64oc_id\x18\x01 \x03(\x05\x32\x42\n\x0eSemanticSearch\x12\x30\n\tinference\x12\x0f.pyInferenceReq\x1a\x10.pyInferenceResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sementic_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PYINFERENCEREQ']._serialized_start=25
  _globals['_PYINFERENCEREQ']._serialized_end=56
  _globals['_PYINFERENCERESP']._serialized_start=58
  _globals['_PYINFERENCERESP']._serialized_end=91
  _globals['_SEMANTICSEARCH']._serialized_start=93
  _globals['_SEMANTICSEARCH']._serialized_end=159
# @@protoc_insertion_point(module_scope)
