// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: semantic_search.proto

#include "./include/semantic_search.pb.h"
#include "./include/semantic_search.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* SemanticSearch_method_names[] = {
  "/SemanticSearch/inference",
};

std::unique_ptr< SemanticSearch::Stub> SemanticSearch::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SemanticSearch::Stub> stub(new SemanticSearch::Stub(channel, options));
  return stub;
}

SemanticSearch::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_inference_(SemanticSearch_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SemanticSearch::Stub::inference(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::pyInferenceResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pyInferenceReq, ::pyInferenceResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_inference_, context, request, response);
}

void SemanticSearch::Stub::async::inference(::grpc::ClientContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pyInferenceReq, ::pyInferenceResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_inference_, context, request, response, std::move(f));
}

void SemanticSearch::Stub::async::inference(::grpc::ClientContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_inference_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pyInferenceResp>* SemanticSearch::Stub::PrepareAsyncinferenceRaw(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pyInferenceResp, ::pyInferenceReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_inference_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pyInferenceResp>* SemanticSearch::Stub::AsyncinferenceRaw(::grpc::ClientContext* context, const ::pyInferenceReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncinferenceRaw(context, request, cq);
  result->StartCall();
  return result;
}

SemanticSearch::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SemanticSearch_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SemanticSearch::Service, ::pyInferenceReq, ::pyInferenceResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SemanticSearch::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pyInferenceReq* req,
             ::pyInferenceResp* resp) {
               return service->inference(ctx, req, resp);
             }, this)));
}

SemanticSearch::Service::~Service() {
}

::grpc::Status SemanticSearch::Service::inference(::grpc::ServerContext* context, const ::pyInferenceReq* request, ::pyInferenceResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


