// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: semantic_search.proto
// Protobuf C++ Version: 6.31.0

#include "./include/semantic_search.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr pyInferenceResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : doc_id_{},
        _doc_id_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR pyInferenceResp::pyInferenceResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(pyInferenceResp_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct pyInferenceRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR pyInferenceRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~pyInferenceRespDefaultTypeInternal() {}
  union {
    pyInferenceResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 pyInferenceRespDefaultTypeInternal _pyInferenceResp_default_instance_;

inline constexpr pyInferenceReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        query_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR pyInferenceReq::pyInferenceReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(pyInferenceReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct pyInferenceReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR pyInferenceReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~pyInferenceReqDefaultTypeInternal() {}
  union {
    pyInferenceReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 pyInferenceReqDefaultTypeInternal _pyInferenceReq_default_instance_;
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_semantic_5fsearch_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_semantic_5fsearch_2eproto = nullptr;
const ::uint32_t
    TableStruct_semantic_5fsearch_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::pyInferenceReq, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::pyInferenceReq, _impl_.query_),
        0,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::pyInferenceResp, _impl_.doc_id_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::pyInferenceReq)},
        {5, sizeof(::pyInferenceResp)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_pyInferenceReq_default_instance_._instance,
    &::_pyInferenceResp_default_instance_._instance,
};
const char descriptor_table_protodef_semantic_5fsearch_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025semantic_search.proto\"\037\n\016pyInferenceRe"
    "q\022\r\n\005query\030\001 \001(\t\"!\n\017pyInferenceResp\022\016\n\006d"
    "oc_id\030\001 \003(\0052B\n\016SemanticSearch\0220\n\tinferen"
    "ce\022\017.pyInferenceReq\032\020.pyInferenceResp\"\000b"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_semantic_5fsearch_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_semantic_5fsearch_2eproto = {
    false,
    false,
    167,
    descriptor_table_protodef_semantic_5fsearch_2eproto,
    "semantic_search.proto",
    &descriptor_table_semantic_5fsearch_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_semantic_5fsearch_2eproto::offsets,
    file_level_enum_descriptors_semantic_5fsearch_2eproto,
    file_level_service_descriptors_semantic_5fsearch_2eproto,
};
// ===================================================================

class pyInferenceReq::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<pyInferenceReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(pyInferenceReq, _impl_._has_bits_);
};

pyInferenceReq::pyInferenceReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, pyInferenceReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pyInferenceReq)
}
PROTOBUF_NDEBUG_INLINE pyInferenceReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::pyInferenceReq& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        query_(arena, from.query_) {}

pyInferenceReq::pyInferenceReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const pyInferenceReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, pyInferenceReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  pyInferenceReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:pyInferenceReq)
}
PROTOBUF_NDEBUG_INLINE pyInferenceReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        query_(arena) {}

inline void pyInferenceReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
pyInferenceReq::~pyInferenceReq() {
  // @@protoc_insertion_point(destructor:pyInferenceReq)
  SharedDtor(*this);
}
inline void pyInferenceReq::SharedDtor(MessageLite& self) {
  pyInferenceReq& this_ = static_cast<pyInferenceReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.query_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL pyInferenceReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) pyInferenceReq(arena);
}
constexpr auto pyInferenceReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(pyInferenceReq),
                                            alignof(pyInferenceReq));
}
constexpr auto pyInferenceReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_pyInferenceReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &pyInferenceReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<pyInferenceReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &pyInferenceReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<pyInferenceReq>(), &pyInferenceReq::ByteSizeLong,
              &pyInferenceReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(pyInferenceReq, _impl_._cached_size_),
          false,
      },
      &pyInferenceReq::kDescriptorMethods,
      &descriptor_table_semantic_5fsearch_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull pyInferenceReq_class_data_ =
        pyInferenceReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
pyInferenceReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&pyInferenceReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(pyInferenceReq_class_data_.tc_table);
  return pyInferenceReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 28, 2>
pyInferenceReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(pyInferenceReq, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    pyInferenceReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pyInferenceReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string query = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(pyInferenceReq, _impl_.query_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string query = 1;
    {PROTOBUF_FIELD_OFFSET(pyInferenceReq, _impl_.query_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\5\0\0\0\0\0\0"
    "pyInferenceReq"
    "query"
  }},
};
PROTOBUF_NOINLINE void pyInferenceReq::Clear() {
// @@protoc_insertion_point(message_clear_start:pyInferenceReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.query_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL pyInferenceReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const pyInferenceReq& this_ = static_cast<const pyInferenceReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL pyInferenceReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const pyInferenceReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:pyInferenceReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string query = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_query().empty()) {
      const ::std::string& _s = this_._internal_query();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pyInferenceReq.query");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pyInferenceReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t pyInferenceReq::ByteSizeLong(const MessageLite& base) {
  const pyInferenceReq& this_ = static_cast<const pyInferenceReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t pyInferenceReq::ByteSizeLong() const {
  const pyInferenceReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pyInferenceReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string query = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_query().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_query());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void pyInferenceReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<pyInferenceReq*>(&to_msg);
  auto& from = static_cast<const pyInferenceReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pyInferenceReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_query().empty()) {
      _this->_internal_set_query(from._internal_query());
    } else {
      if (_this->_impl_.query_.IsDefault()) {
        _this->_internal_set_query("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void pyInferenceReq::CopyFrom(const pyInferenceReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pyInferenceReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void pyInferenceReq::InternalSwap(pyInferenceReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.query_, &other->_impl_.query_, arena);
}

::google::protobuf::Metadata pyInferenceReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class pyInferenceResp::_Internal {
 public:
};

pyInferenceResp::pyInferenceResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, pyInferenceResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pyInferenceResp)
}
PROTOBUF_NDEBUG_INLINE pyInferenceResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::pyInferenceResp& from_msg)
      : doc_id_{visibility, arena, from.doc_id_},
        _doc_id_cached_byte_size_{0},
        _cached_size_{0} {}

pyInferenceResp::pyInferenceResp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const pyInferenceResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, pyInferenceResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  pyInferenceResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:pyInferenceResp)
}
PROTOBUF_NDEBUG_INLINE pyInferenceResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : doc_id_{visibility, arena},
        _doc_id_cached_byte_size_{0},
        _cached_size_{0} {}

inline void pyInferenceResp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
pyInferenceResp::~pyInferenceResp() {
  // @@protoc_insertion_point(destructor:pyInferenceResp)
  SharedDtor(*this);
}
inline void pyInferenceResp::SharedDtor(MessageLite& self) {
  pyInferenceResp& this_ = static_cast<pyInferenceResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL pyInferenceResp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) pyInferenceResp(arena);
}
constexpr auto pyInferenceResp::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(pyInferenceResp, _impl_.doc_id_) +
          decltype(pyInferenceResp::_impl_.doc_id_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(pyInferenceResp), alignof(pyInferenceResp), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&pyInferenceResp::PlacementNew_,
                                 sizeof(pyInferenceResp),
                                 alignof(pyInferenceResp));
  }
}
constexpr auto pyInferenceResp::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_pyInferenceResp_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &pyInferenceResp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<pyInferenceResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &pyInferenceResp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<pyInferenceResp>(), &pyInferenceResp::ByteSizeLong,
              &pyInferenceResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(pyInferenceResp, _impl_._cached_size_),
          false,
      },
      &pyInferenceResp::kDescriptorMethods,
      &descriptor_table_semantic_5fsearch_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull pyInferenceResp_class_data_ =
        pyInferenceResp::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
pyInferenceResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&pyInferenceResp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(pyInferenceResp_class_data_.tc_table);
  return pyInferenceResp_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
pyInferenceResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    pyInferenceResp_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pyInferenceResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int32 doc_id = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(pyInferenceResp, _impl_.doc_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int32 doc_id = 1;
    {PROTOBUF_FIELD_OFFSET(pyInferenceResp, _impl_.doc_id_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void pyInferenceResp::Clear() {
// @@protoc_insertion_point(message_clear_start:pyInferenceResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.doc_id_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL pyInferenceResp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const pyInferenceResp& this_ = static_cast<const pyInferenceResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL pyInferenceResp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const pyInferenceResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:pyInferenceResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated int32 doc_id = 1;
  {
    int byte_size = this_._impl_._doc_id_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, this_._internal_doc_id(), byte_size, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pyInferenceResp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t pyInferenceResp::ByteSizeLong(const MessageLite& base) {
  const pyInferenceResp& this_ = static_cast<const pyInferenceResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t pyInferenceResp::ByteSizeLong() const {
  const pyInferenceResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pyInferenceResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated int32 doc_id = 1;
    {
      total_size +=
          ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
              this_._internal_doc_id(), 1,
              this_._impl_._doc_id_cached_byte_size_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void pyInferenceResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<pyInferenceResp*>(&to_msg);
  auto& from = static_cast<const pyInferenceResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pyInferenceResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_doc_id()->MergeFrom(from._internal_doc_id());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void pyInferenceResp::CopyFrom(const pyInferenceResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pyInferenceResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void pyInferenceResp::InternalSwap(pyInferenceResp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.doc_id_.InternalSwap(&other->_impl_.doc_id_);
}

::google::protobuf::Metadata pyInferenceResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_semantic_5fsearch_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
